version: '3.1'

services:
  
  rails:
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    container_name: oasisform
    restart: always
    env_file:
      - './env/.env.dev.rails'    
    volumes:
      - ./oasisform:/home/oasisform
    ports:
      - "3001:3000"