version: '3.1'

services:
  
  rails:
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    container_name: oasisform
    restart: always
    environment:
      #- API_KEY=
      - ORDER_EMAIL=liborders@mail.wvu.edu
      - OASIS_URL=https://oasis-services.proquest.com/order/      
      - SECRET_KEY_BASE=e9f0887b29e854a81e8dbdb3090b9a1b54ba2201c41b52966df6100ce672a70ed6c4c1a029ccb28cfc162a52ae2e68543b675eb5d4b703ecee903ebd8d66a6bb    
      - TERM=xterm
      # - RAILS_ENV=production #uncomment for production
    volumes:
      - .:/home/oasisform
    ports:
      - "3001:3000"
  
